float numero1=15;
float numero2=25;
float suma = numero1 + numero2;
println("El resultado de la suma es: " + suma);
float resta = numero1 - numero2;
println("El resultado de la resta es: " + resta);
float multiplicacion = numero1 * numero2;
println("El resultado de la multiplicación es: " + multiplicacion);
float division = numero1 / numero2;
println("El resultado de la division es: " + division);
